title: Finance Hub
description: Your finance tips and tricks
baseurl: ""  # Change to "/finance-hub" if using GitHub Pages
url: "http://localhost:4000"  # Update to your domain when deploying
markdown: kramdown
permalink: /:categories/:title/
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
defaults:
  - scope:
      path: ""
      type: portfolio
    values:
      layout: portfolio
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      
